### ISSUE TITLE
mxnet problem

### ISSUE THREAD

**Issue by wufengbin123** [tonysy/Deep-Feature-Flow-Segmentation#12]
[11:10:10] src/base.cc:51: Upgrade advisory: this mxnet has been built against cuda library version 9000, which is older than the oldest version tested by CI (10000).  Set MXNET_CUDA_LIB_CHECKING=0 to quiet this warning.
learning rate from ``lr_scheduler`` has been overwritten by ``learning_rate`` in optimizer.
Traceback (most recent call last):
  File "./experiments/deeplab/deeplab_train_test.py", line 23, in <module>
    train.main()
  File "./experiments/deeplab/../../deeplab/train.py", line 209, in main
    config.TRAIN.begin_epoch, config.TRAIN.end_epoch, config.TRAIN.lr, config.TRAIN.lr_step)
  File "./experiments/deeplab/../../deeplab/train.py", line 203, in train_net
    arg_params=arg_params, aux_params=aux_params, begin_epoch=begin_epoch, num_epoch=end_epoch)
  File "./experiments/deeplab/../../deeplab/core/module.py", line 976, in fit
    self.update_metric(eval_metric, data_batch.label)
  File "./experiments/deeplab/../../deeplab/core/module.py", line 1068, in update_metric
    self._curr_module.update_metric(eval_metric, labels)
  File "./experiments/deeplab/../../deeplab/core/module.py", line 665, in update_metric
    self._exec_group.update_metric(eval_metric, labels)
  File "./experiments/deeplab/../../deeplab/core/DataParallelExecutorGroup.py", line 490, in update_metric
    eval_metric.update(labels, texec.outputs)
  File "/usr/local/anaconda3/envs/py27/lib/python2.7/site-packages/mxnet/metric.py", line 363, in update
    metric.update(labels, preds)
  File "./experiments/deeplab/../../deeplab/core/metric.py", line 28, in update
    pred = pred.asnumpy().reshape((pred.shape[0], pred.shape[1], -1)).transpose((0, 2, 1))
  File "/usr/local/anaconda3/envs/py27/lib/python2.7/site-packages/mxnet/ndarray/ndarray.py", line 2535, in asnumpy
    ctypes.c_size_t(data.size)))
  File "/usr/local/anaconda3/envs/py27/lib/python2.7/site-packages/mxnet/base.py", line 255, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [11:10:13] src/operator/fusion/fused_op.cu:604: Check failed: compileResult == NVRTC_SUCCESS (5 vs. 0) : NVRTC Compilation failed. Please set environment variable MXNET_USE_FUSION to 0.
nvrtc: error: invalid value for --gpu-architecture (-arch)

Stack trace:
  [bt] (0) /usr/local/anaconda3/envs/py27/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x6b41eb) [0x7f78887981eb]
  [bt] (1) /usr/local/anaconda3/envs/py27/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x44fb5a6) [0x7f788c5df5a6]
  [bt] (2) /usr/local/anaconda3/envs/py27/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x4505d87) [0x7f788c5e9d87]
  [bt] (3) /usr/local/anaconda3/envs/py27/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x37d69b9) [0x7f788b8ba9b9]
  [bt] (4) /usr/local/anaconda3/envs/py27/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x37e33d5) [0x7f788b8c73d5]
  [bt] (5) /usr/local/anaconda3/envs/py27/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x37bf6d1) [0x7f788b8a36d1]
  [bt] (6) /usr/local/anaconda3/envs/py27/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x37c2c10) [0x7f788b8a6c10]
  [bt] (7) /usr/local/anaconda3/envs/py27/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x37c2ea6) [0x7f788b8a6ea6]
  [bt] (8) /usr/local/anaconda3/envs/py27/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x37bde84) [0x7f788b8a1e84]
I installed mxnet-cu90 and meet this problem,Can anyone help me?Thank you .

**Comment by tonysy** [comment]
I think this issue is related to the hardware and software configuration, please raise an issue in the MXNet repo, and you may get help from their community.
